//! Create-path orchestration with scheduler placement and stale-operation safety.
//!
//! Composes policy, quota, regional and cell scheduling, metadata commit,
//! and audit emission into one control-plane create path. Retries converge
//! to a single outcome through idempotency-key dedup and operation-identity
//! checks instead of double-applying.
//!
//! The orchestrator is synchronous and holds no async guards. Audit emission
//! stays best-effort: a saturated sink never fails placement or create.

use std::sync::Arc;

use hashbrown::HashMap;
use parking_lot::RwLock;
use serde::{Deserialize, Serialize};

use crate::cell_scheduler::{CellScheduler, CellSchedulerError, CellSchedulerRequest, HostInfo};
use crate::event_bus::{AuditEventBuilder, AuditEventSink};
use crate::identity::{
    AuditEventDetails, AuditEventKind, CellId, FencingToken, Hlc, HostId, OperationId, PrincipalId,
    SandboxId, TenantId,
};
use crate::metadata::{
    PlacementInfo, ResourceLimits, SandboxMetadata, SandboxState, TransitionError,
};
use crate::overcommit::ServiceClass;
use crate::policy::{PolicyAction, PolicyEngine, PolicyOutcome};
use crate::quota::QuotaEngine;
use crate::runtime::RuntimeType;
use crate::scheduler::{RegionalScheduler, ScheduleTraceContext, SchedulerError, SchedulerRequest};
use crate::types::new_ulid;

/// Returns true when an idempotency key matches the API contract.
///
/// Keys are 1-256 bytes of ASCII alphanumeric plus hyphen and underscore.
/// This is the production gate used by the create path; the contract test
/// in `tests/contract_v2.rs` pins the same pattern.
pub fn is_valid_idempotency_key(key: &str) -> bool {
    if key.is_empty() || key.len() > 256 {
        return false;
    }
    key.chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
}

/// Request to create a sandbox through the integrated control-plane path.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CreateRequest {
    /// Tenant that owns the sandbox.
    pub tenant_id: TenantId,
    /// Authenticated caller.
    pub principal: PrincipalId,
    /// Target sandbox identity. Generated by the caller before admission.
    pub sandbox_id: SandboxId,
    /// Container image or rootfs identifier.
    pub image: String,
    /// Requested runtime backend.
    pub runtime: Option<RuntimeType>,
    /// Requested vCPUs.
    pub vcpus: u32,
    /// Requested memory in MB.
    pub memory_mb: u64,
    /// Requested disk in MB for cell placement.
    pub disk_mb: u64,
    /// Snapshot to restore from.
    pub snapshot_id: Option<String>,
    /// Preferred region for scoring.
    pub preferred_region: Option<crate::identity::RegionId>,
    /// Failure domains to avoid for spread.
    pub avoid_failure_domains: Vec<String>,
    /// Request trace for audit and trace correlation.
    pub trace_id: Option<String>,
    /// Operation identity for retry convergence.
    pub operation_id: OperationId,
    /// Client idempotency key for safe retry.
    pub idempotency_key: Option<String>,
    /// Fencing token for the Pending to Scheduled commit.
    pub fencing_token: Option<FencingToken>,
    /// Scheduling service class for this sandbox.
    ///
    /// `None` (the default) packs latency-sensitive: strict no-overcommit.
    /// The API boundary resolves this from tenant policy via
    /// [`crate::overcommit::resolve_service_class`] once the tenant
    /// registry is wired into admission; the orchestrator threads the
    /// resolved value into cell placement unchanged.
    #[serde(default)]
    pub service_class: Option<ServiceClass>,
}

/// Persisted placement result for a successful create.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct CreateOutcome {
    /// Metadata record after the Pending to Scheduled commit.
    pub metadata: SandboxMetadata,
    /// Selected cell.
    pub cell_id: CellId,
    /// Selected host.
    pub host_id: HostId,
    /// Regional placement reason for traces and audit.
    pub regional_reason: String,
    /// Cell placement reason for traces and audit.
    pub cell_reason: String,
    /// True when this outcome is an idempotent replay without new side effects.
    pub replayed: bool,
}

/// Typed create-path failures.
///
/// Rejection reasons stay typed so callers map them to traces and audit
/// without parsing error strings. Scheduler rejections keep their taxonomy.
#[derive(Debug, Clone, thiserror::Error, PartialEq)]
pub enum CreateError {
    /// Idempotency key violates the contract pattern.
    #[error("invalid idempotency key: {reason}")]
    InvalidIdempotencyKey { reason: String },

    /// Same key was already used with a different request body.
    #[error("idempotency conflict for key {key}")]
    IdempotencyConflict { key: String },

    /// Operation identity was already processed for a different outcome.
    #[error("stale operation: {op_id}")]
    StaleOperation { op_id: String },

    /// Policy denied create.
    #[error("policy denied: {reason}")]
    PolicyDenied { reason: String },

    /// Quota exhausted before placement.
    #[error("quota exceeded: {resource} limit={limit} current={current}")]
    QuotaExceeded {
        resource: String,
        limit: u64,
        current: u64,
    },

    /// Regional placement failed.
    #[error("regional placement failed: {0}")]
    Regional(Box<SchedulerError>),

    /// Cell placement failed.
    #[error("cell placement failed: {0}")]
    Cell(Box<CellSchedulerError>),

    /// Lifecycle commit failed.
    #[error("commit failed: {0}")]
    Transition(Box<TransitionError>),
}

impl From<SchedulerError> for CreateError {
    fn from(err: SchedulerError) -> Self {
        Self::Regional(Box::new(err))
    }
}

impl From<CellSchedulerError> for CreateError {
    fn from(err: CellSchedulerError) -> Self {
        Self::Cell(Box::new(err))
    }
}

impl From<TransitionError> for CreateError {
    fn from(err: TransitionError) -> Self {
        match err {
            TransitionError::StaleOperation { op_id } => Self::StaleOperation { op_id },
            other => Self::Transition(Box::new(other)),
        }
    }
}

impl From<CreateError> for crate::error::SandboxError {
    fn from(err: CreateError) -> Self {
        match err {
            CreateError::InvalidIdempotencyKey { reason } => {
                crate::error::SandboxError::BadRequest(reason)
            }
            CreateError::IdempotencyConflict { key } => {
                crate::error::SandboxError::Conflict(format!("idempotency conflict for key {key}"))
            }
            CreateError::StaleOperation { op_id } => {
                crate::error::SandboxError::OperationStale(op_id)
            }
            CreateError::PolicyDenied { reason } => {
                crate::error::SandboxError::PolicyDenied { reason }
            }
            CreateError::QuotaExceeded {
                resource,
                limit,
                current,
            } => crate::error::SandboxError::QuotaExceeded {
                resource,
                limit,
                current,
            },
            // Throttling is owned by the `From<SchedulerError>` conversions in
            // `error.rs` so the create path cannot drift from direct callers.
            CreateError::Regional(reason) => (*reason).into(),
            CreateError::Cell(reason) => (*reason).into(),
            CreateError::Transition(reason) => {
                crate::error::SandboxError::InvalidStateTransition(reason.to_string())
            }
        }
    }
}

/// Request fingerprint for idempotency conflict detection.
///
/// Excludes per-attempt identity (sandbox id, trace, operation, fencing
/// token) so a retry with a fresh operation id but the same body still
/// converges to the stored outcome. A different body with the same key is
/// a conflict. Principal, region preference, and failure-domain spread
/// affect admission and placement, so they are part of the fingerprint.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
struct CreateFingerprint {
    tenant: String,
    principal: String,
    image: String,
    runtime: Option<String>,
    vcpus: u32,
    memory_mb: u64,
    disk_mb: u64,
    snapshot_id: Option<String>,
    preferred_region: Option<String>,
    avoid_failure_domains: Vec<String>,
}

impl CreateFingerprint {
    fn of(req: &CreateRequest) -> Self {
        let mut avoid = req.avoid_failure_domains.clone();
        avoid.sort_unstable();
        Self {
            tenant: req.tenant_id.as_str().to_string(),
            principal: req.principal.as_str().to_string(),
            image: req.image.clone(),
            runtime: req.runtime.map(|r| format!("{r:?}")),
            vcpus: req.vcpus,
            memory_mb: req.memory_mb,
            disk_mb: req.disk_mb,
            snapshot_id: req.snapshot_id.clone(),
            preferred_region: req
                .preferred_region
                .as_ref()
                .map(|r| r.as_str().to_string()),
            avoid_failure_domains: avoid,
        }
    }
}

#[derive(Debug, Clone)]
enum DedupEntry {
    InProgress,
    Completed {
        fingerprint: CreateFingerprint,
        outcome: Box<CreateOutcome>,
    },
}

/// Completed operation outcome for same-operation replay.
///
/// Covers keyless creates where no idempotency key exists to correlate a
/// partition retry. The fingerprint guards against operation-id reuse with
/// a different body, which surfaces as `StaleOperation`.
#[derive(Debug, Clone)]
struct OpCompleted {
    tenant: String,
    key: String,
    fingerprint: CreateFingerprint,
    outcome: Box<CreateOutcome>,
}

struct Inner {
    by_key: HashMap<(String, String), DedupEntry>,
    op_to_key: HashMap<String, (String, String)>,
    op_completed: HashMap<String, OpCompleted>,
}

/// Tenant-scoped idempotency and operation dedup store.
///
/// Maps idempotency keys to completed outcomes and tracks processed
/// operation ids so partition retries converge to one outcome. The store is
/// in-memory for the integrated control-plane path; a durable store can
/// replace it without changing the orchestrator contract.
///
/// All claim/check/insert steps hold the single inner write lock, so two
/// concurrent creates with the same key resolve to one winner without
/// double-applying. The lock is never held across scheduling, quota, or
/// audit I/O.
pub struct IdempotencyStore {
    inner: RwLock<Inner>,
}

impl Default for IdempotencyStore {
    fn default() -> Self {
        Self::new()
    }
}

impl IdempotencyStore {
    /// Creates an empty store.
    pub fn new() -> Self {
        Self {
            inner: RwLock::new(Inner {
                by_key: HashMap::new(),
                op_to_key: HashMap::new(),
                op_completed: HashMap::new(),
            }),
        }
    }

    /// Returns the number of tracked keys (including in-progress).
    pub fn len(&self) -> usize {
        self.inner.read().by_key.len()
    }

    /// Returns true when no keys are tracked.
    pub fn is_empty(&self) -> bool {
        self.inner.read().by_key.is_empty()
    }

    fn key_of(req: &CreateRequest) -> Option<(String, String)> {
        req.idempotency_key
            .clone()
            .map(|k| (req.tenant_id.as_str().to_string(), k))
    }
}

impl std::fmt::Debug for IdempotencyStore {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("IdempotencyStore")
            .field("keys", &self.len())
            .finish()
    }
}

/// Control-plane create orchestrator.
///
/// Owns policy, quota, audit, and dedup state. Schedulers and inventory
/// snapshots are supplied per call so tests inject deterministic cells and
/// hosts without a global registry.
pub struct CreateOrchestrator {
    policy: Arc<PolicyEngine>,
    quota: Arc<QuotaEngine>,
    audit_sink: Arc<dyn AuditEventSink>,
    hlc: Arc<Hlc>,
    dedup: Arc<IdempotencyStore>,
}

impl CreateOrchestrator {
    /// Creates an orchestrator sharing policy, quota, audit, and dedup state.
    pub fn new(
        policy: Arc<PolicyEngine>,
        quota: Arc<QuotaEngine>,
        audit_sink: Arc<dyn AuditEventSink>,
        hlc: Arc<Hlc>,
        dedup: Arc<IdempotencyStore>,
    ) -> Self {
        Self {
            policy,
            quota,
            audit_sink,
            hlc,
            dedup,
        }
    }

    /// Returns the dedup store for inspection in tests.
    pub fn dedup(&self) -> &IdempotencyStore {
        &self.dedup
    }

    /// Creates a sandbox through policy, quota, two-stage placement, and commit.
    ///
    /// On success the metadata record is in `Scheduled` with persisted
    /// region, cell, host, and runtime placement. Placement decisions and
    /// rejections carry trace, operation, and idempotency identity in audit
    /// events and tracing spans. Audit emission is best-effort and never
    /// fails create. Quota reservations release when placement or commit
    /// fails after quota admission.
    #[tracing::instrument(skip(self, req, regional, cells, cell_scheduler, hosts_for_cell), fields(
        tenant_id = %req.tenant_id,
        sandbox_id = %req.sandbox_id,
        operation_id = %req.operation_id
    ))]
    pub fn create(
        &self,
        req: &CreateRequest,
        regional: &RegionalScheduler,
        cells: &[crate::scheduler::CellInfo],
        cell_scheduler: &CellScheduler,
        hosts_for_cell: &dyn Fn(&CellId) -> Vec<HostInfo>,
    ) -> Result<CreateOutcome, CreateError> {
        if let Some(ref key) = req.idempotency_key
            && !is_valid_idempotency_key(key)
        {
            return Err(CreateError::InvalidIdempotencyKey {
                reason: format!(
                    "key must be 1-256 ASCII alphanumeric, hyphen, or underscore: {key:?}"
                ),
            });
        }

        let fingerprint = CreateFingerprint::of(req);
        let op_str = req.operation_id.as_str().to_string();
        let req_tenant = req.tenant_id.as_str().to_string();
        let req_key = req.idempotency_key.clone().unwrap_or_default();
        let key_opt = IdempotencyStore::key_of(req);

        {
            let mut inner = self.dedup.inner.write();
            if let Some(completed) = inner.op_completed.get(&op_str) {
                if completed.tenant == req_tenant
                    && completed.key == req_key
                    && completed.fingerprint == fingerprint
                {
                    let mut replayed = completed.outcome.as_ref().clone();
                    replayed.replayed = true;
                    tracing::info!("create same-operation replay without new side effects");
                    return Ok(replayed);
                }
                return Err(CreateError::StaleOperation { op_id: op_str });
            }
            if let Some(key) = &key_opt
                && let Some(entry) = inner.by_key.get(key)
            {
                match entry {
                    DedupEntry::Completed {
                        fingerprint: stored_fp,
                        outcome,
                    } => {
                        if *stored_fp == fingerprint {
                            let mut replayed = outcome.as_ref().clone();
                            replayed.replayed = true;
                            tracing::info!("create idempotent replay without new side effects");
                            return Ok(replayed);
                        }
                        return Err(CreateError::IdempotencyConflict { key: key.1.clone() });
                    }
                    DedupEntry::InProgress => {
                        return Err(CreateError::StaleOperation { op_id: op_str });
                    }
                }
            }
            if let Some((stored_tenant, stored_key)) = inner.op_to_key.get(&op_str)
                && (stored_tenant != &req_tenant || stored_key != &req_key)
            {
                return Err(CreateError::StaleOperation { op_id: op_str });
            }
            if let Some(key) = &key_opt {
                inner
                    .by_key
                    .entry(key.clone())
                    .or_insert(DedupEntry::InProgress);
                inner
                    .op_to_key
                    .entry(op_str.clone())
                    .or_insert((req_tenant.clone(), req_key.clone()));
            } else {
                inner
                    .op_to_key
                    .entry(op_str.clone())
                    .or_insert((req_tenant.clone(), String::new()));
            }
        }

        let result = self.create_inner(req, regional, cells, cell_scheduler, hosts_for_cell);

        match result {
            Ok(outcome) => {
                let mut inner = self.dedup.inner.write();
                let completed = OpCompleted {
                    tenant: req_tenant,
                    key: req_key,
                    fingerprint,
                    outcome: Box::new(outcome.clone()),
                };
                inner.op_completed.insert(op_str.clone(), completed);
                if let Some(key) = key_opt {
                    inner.by_key.insert(
                        key.clone(),
                        DedupEntry::Completed {
                            fingerprint: CreateFingerprint::of(req),
                            outcome: Box::new(outcome.clone()),
                        },
                    );
                    inner.op_to_key.insert(op_str, (key.0, key.1));
                } else {
                    inner
                        .op_to_key
                        .insert(op_str, (req.tenant_id.as_str().to_string(), String::new()));
                }
                Ok(outcome)
            }
            Err(err) => {
                let mut inner = self.dedup.inner.write();
                inner.op_to_key.remove(&op_str);
                if let Some(key) = key_opt
                    && matches!(inner.by_key.get(&key), Some(DedupEntry::InProgress))
                {
                    inner.by_key.remove(&key);
                }
                Err(err)
            }
        }
    }

    fn create_inner(
        &self,
        req: &CreateRequest,
        regional: &RegionalScheduler,
        cells: &[crate::scheduler::CellInfo],
        cell_scheduler: &CellScheduler,
        hosts_for_cell: &dyn Fn(&CellId) -> Vec<HostInfo>,
    ) -> Result<CreateOutcome, CreateError> {
        let context = ScheduleTraceContext {
            trace_id: req.trace_id.clone(),
            operation_id: Some(req.operation_id.clone()),
            idempotency_key: req.idempotency_key.clone(),
        };

        let decision = self
            .policy
            .evaluate(&req.principal, &req.tenant_id, PolicyAction::Create);
        let policy_epoch = decision.policy_epoch;
        let outcome_str = match &decision.outcome {
            PolicyOutcome::Allow => "allow",
            PolicyOutcome::Deny { .. } => "deny",
        };
        let reason = match &decision.outcome {
            PolicyOutcome::Deny { reason } => Some(reason.clone()),
            PolicyOutcome::Allow => None,
        };
        self.emit_policy_decision(req, &decision, outcome_str, reason.clone());
        if let PolicyOutcome::Deny { reason } = decision.outcome {
            tracing::warn!(%reason, "create rejected by policy");
            return Err(CreateError::PolicyDenied { reason });
        }

        let quota_decision = self
            .quota
            .check_create(&req.tenant_id, req.vcpus, req.memory_mb);
        if !quota_decision.allowed {
            let resource = quota_decision.resource.clone().unwrap_or_default();
            self.emit_quota_rejection(req, &resource, quota_decision.limit, quota_decision.current);
            tracing::warn!(%resource, "create rejected by quota");
            return Err(CreateError::QuotaExceeded {
                resource,
                limit: quota_decision.limit,
                current: quota_decision.current,
            });
        }

        let sched_req = SchedulerRequest {
            tenant_id: req.tenant_id.clone(),
            vcpus: req.vcpus,
            memory_mb: req.memory_mb,
            runtime: req.runtime,
            image: req.image.clone(),
            snapshot_id: req.snapshot_id.clone(),
            preferred_region: req.preferred_region.clone(),
            avoid_failure_domains: req.avoid_failure_domains.clone(),
            sandbox_id: req.sandbox_id.as_str().to_string(),
        };
        let regional_resp = match regional.schedule_with_context(&sched_req, cells, Some(&context))
        {
            Ok(resp) => resp,
            Err(err) => {
                self.quota.release(&req.tenant_id, req.vcpus, req.memory_mb);
                tracing::warn!(reason = %err, "create regional placement rejected");
                return Err(err.into());
            }
        };
        let cell_id = regional_resp.cell_id.clone().ok_or_else(|| {
            self.quota.release(&req.tenant_id, req.vcpus, req.memory_mb);
            CreateError::Regional(Box::new(SchedulerError::NoCellSatisfiesConstraints {
                reason: "regional placement returned no cell".into(),
            }))
        })?;

        let hosts = hosts_for_cell(&cell_id);
        let cell_req = CellSchedulerRequest {
            sandbox_id: req.sandbox_id.as_str().to_string(),
            vcpus: req.vcpus,
            memory_mb: req.memory_mb,
            disk_mb: req.disk_mb,
            runtime: req.runtime,
            image: req.image.clone(),
            snapshot_id: req.snapshot_id.clone(),
            is_restore: false,
            service_class: req.service_class.unwrap_or_default(),
        };
        let cell_resp =
            match cell_scheduler.schedule_with_context(&cell_req, &hosts, Some(&context)) {
                Ok(resp) => resp,
                Err(err) => {
                    self.quota.release(&req.tenant_id, req.vcpus, req.memory_mb);
                    tracing::warn!(reason = %err, "create cell placement rejected");
                    return Err(err.into());
                }
            };
        let host_id = cell_resp.host_id.clone().ok_or_else(|| {
            self.quota.release(&req.tenant_id, req.vcpus, req.memory_mb);
            CreateError::Cell(Box::new(CellSchedulerError::NoHostSatisfiesConstraints {
                reason: "cell placement returned no host".into(),
            }))
        })?;

        let region = regional_resp
            .placement
            .as_ref()
            .and_then(|p| p.region.clone());
        let placement = PlacementInfo {
            region,
            cell: Some(cell_id.as_str().to_string()),
            host: Some(host_id.as_str().to_string()),
            runtime_backend: req.runtime,
            network_identity: None,
        };

        let mut metadata = SandboxMetadata::new(
            req.sandbox_id.clone(),
            req.tenant_id.clone(),
            req.image.clone(),
            req.runtime,
            ResourceLimits {
                memory_mb: req.memory_mb,
                vcpus: req.vcpus,
                ..ResourceLimits::default()
            },
            None,
        );
        metadata.actor_identity = Some(req.principal.clone());
        metadata.policy_epoch = Some(policy_epoch);
        metadata.placement = Some(placement.clone());

        if let Err(err) = metadata.commit_with_operation(
            SandboxState::Pending,
            SandboxState::Scheduled,
            req.fencing_token,
            Some(req.operation_id.clone()),
            req.idempotency_key.clone(),
        ) {
            self.quota.release(&req.tenant_id, req.vcpus, req.memory_mb);
            tracing::warn!(reason = %err, "create commit rejected");
            return Err(err.into());
        }

        self.emit_lifecycle(req, &metadata, &placement);

        tracing::info!(
            cell_id = %cell_id.as_str(),
            host_id = %host_id.as_str(),
            regional_reason = ?regional_resp.reason,
            cell_reason = ?cell_resp.reason,
            "create placed on two-stage path"
        );

        Ok(CreateOutcome {
            metadata,
            cell_id,
            host_id,
            regional_reason: format!("{:?}", regional_resp.reason),
            cell_reason: format!("{:?}", cell_resp.reason),
            replayed: false,
        })
    }

    fn emit_policy_decision(
        &self,
        req: &CreateRequest,
        decision: &crate::policy::PolicyDecision,
        outcome: &str,
        reason: Option<String>,
    ) {
        let mut builder =
            AuditEventBuilder::new(Arc::clone(&self.hlc), AuditEventKind::PolicyDecision)
                .sandbox_id(req.sandbox_id.clone())
                .tenant_id(req.tenant_id.clone())
                .principal(req.principal.clone())
                .details(AuditEventDetails::PolicyDecision {
                    decision_id: decision.decision_id.as_str().to_string(),
                    action: PolicyAction::Create.as_str().to_string(),
                    outcome: outcome.to_string(),
                    policy_epoch: decision.policy_epoch,
                    reason,
                })
                .epoch(decision.policy_epoch);
        if let Some(ref trace_id) = req.trace_id {
            builder = builder.trace_id(trace_id.clone());
        }
        builder = builder.operation_id(req.operation_id.clone());
        if let Some(ref key) = req.idempotency_key {
            builder = builder.idempotency_key(key.clone());
        }
        let _ = self.audit_sink.emit(builder.build());
    }

    fn emit_quota_rejection(&self, req: &CreateRequest, resource: &str, limit: u64, current: u64) {
        let mut builder =
            AuditEventBuilder::new(Arc::clone(&self.hlc), AuditEventKind::QuotaRejection)
                .sandbox_id(req.sandbox_id.clone())
                .tenant_id(req.tenant_id.clone())
                .principal(req.principal.clone())
                .details(AuditEventDetails::QuotaRejection {
                    decision_id: new_ulid("pdc"),
                    resource: resource.to_string(),
                    limit,
                    current,
                });
        if let Some(ref trace_id) = req.trace_id {
            builder = builder.trace_id(trace_id.clone());
        }
        builder = builder.operation_id(req.operation_id.clone());
        if let Some(ref key) = req.idempotency_key {
            builder = builder.idempotency_key(key.clone());
        }
        let _ = self.audit_sink.emit(builder.build());
    }

    fn emit_lifecycle(
        &self,
        req: &CreateRequest,
        metadata: &SandboxMetadata,
        placement: &PlacementInfo,
    ) {
        let mut builder =
            AuditEventBuilder::new(Arc::clone(&self.hlc), AuditEventKind::LifecycleTransition)
                .sandbox_id(req.sandbox_id.clone())
                .tenant_id(req.tenant_id.clone())
                .principal(req.principal.clone())
                .from_state(SandboxState::Pending.as_str())
                .to_state(SandboxState::Scheduled.as_str())
                .details(AuditEventDetails::LifecycleTransition {
                    fencing_token: metadata.fencing_token,
                })
                .epoch(metadata.policy_epoch.unwrap_or(0));
        if let Some(ref trace_id) = req.trace_id {
            builder = builder.trace_id(trace_id.clone());
        }
        builder = builder.operation_id(req.operation_id.clone());
        if let Some(ref key) = req.idempotency_key {
            builder = builder.idempotency_key(key.clone());
        }
        if let Some(token) = metadata.fencing_token {
            builder = builder.fencing_token(token);
        }
        let event = builder.build();
        debug_assert_eq!(
            placement.cell,
            metadata.placement.as_ref().and_then(|p| p.cell.clone())
        );
        let _ = self.audit_sink.emit(event);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_request(suffix: &str) -> CreateRequest {
        CreateRequest {
            tenant_id: TenantId::from_string("tnt_create"),
            principal: PrincipalId::new("user:create"),
            sandbox_id: SandboxId::from_string(format!("sbx_create_{suffix}")),
            image: "img:create".into(),
            runtime: Some(RuntimeType::Firecracker),
            vcpus: 2,
            memory_mb: 512,
            disk_mb: 1024,
            snapshot_id: None,
            preferred_region: None,
            avoid_failure_domains: vec![],
            trace_id: None,
            operation_id: OperationId::generate(),
            idempotency_key: None,
            fencing_token: None,
            service_class: None,
        }
    }

    #[test]
    fn valid_keys_pass_contract_pattern() {
        assert!(is_valid_idempotency_key("create-sandbox-001"));
        assert!(is_valid_idempotency_key("abc123_XYZ"));
        assert!(is_valid_idempotency_key("a"));
    }

    #[test]
    fn invalid_keys_fail_contract_pattern() {
        assert!(!is_valid_idempotency_key(""));
        assert!(!is_valid_idempotency_key("has spaces"));
        assert!(!is_valid_idempotency_key("emoji-😀"));
        assert!(!is_valid_idempotency_key(&"k".repeat(257)));
    }

    #[test]
    fn fingerprint_ignores_per_attempt_identity() {
        let mut a = test_request("fp");
        let mut b = test_request("fp");
        b.sandbox_id = SandboxId::from_string("sbx_create_other");
        b.trace_id = Some("trace-1".into());
        b.operation_id = OperationId::generate();
        b.idempotency_key = Some("key-1".into());
        a.idempotency_key = Some("key-1".into());
        assert_eq!(CreateFingerprint::of(&a), CreateFingerprint::of(&b));
    }

    #[test]
    fn fingerprint_distinguishes_body() {
        let a = test_request("fp2");
        let mut b = test_request("fp2");
        b.memory_mb = 1024;
        assert_ne!(CreateFingerprint::of(&a), CreateFingerprint::of(&b));
    }

    #[test]
    fn fingerprint_distinguishes_principal_region_and_spread() {
        let a = test_request("fp3");
        let mut b = test_request("fp3");
        b.principal = PrincipalId::new("user:other");
        assert_ne!(CreateFingerprint::of(&a), CreateFingerprint::of(&b));

        let mut c = test_request("fp3");
        c.preferred_region = Some(crate::identity::RegionId::from_string("rgn_eu"));
        assert_ne!(CreateFingerprint::of(&a), CreateFingerprint::of(&c));

        let mut d = test_request("fp3");
        d.avoid_failure_domains = vec!["fd-1".into()];
        assert_ne!(CreateFingerprint::of(&a), CreateFingerprint::of(&d));
    }

    #[test]
    fn error_maps_stale_operation() {
        let err: CreateError = TransitionError::StaleOperation {
            op_id: "opr_old".into(),
        }
        .into();
        assert!(matches!(err, CreateError::StaleOperation { .. }));
        let sandbox_err: crate::error::SandboxError = err.into();
        assert!(matches!(
            sandbox_err,
            crate::error::SandboxError::OperationStale(_)
        ));
    }

    #[test]
    fn regional_capacity_preserves_retry_hint() {
        for regional in [
            SchedulerError::InsufficientCapacity {
                vcpus: 4,
                memory_mb: 8192,
            },
            SchedulerError::PressureSaturated,
        ] {
            let err = CreateError::Regional(Box::new(regional));
            let sandbox_err: crate::error::SandboxError = err.into();
            match sandbox_err {
                crate::error::SandboxError::PlacementThrottled {
                    retry_after_secs, ..
                } => {
                    assert_eq!(retry_after_secs, crate::error::PLACEMENT_RETRY_AFTER_SECS);
                }
                other => panic!("expected PlacementThrottled, got {other:?}"),
            }
        }
    }

    #[test]
    fn cell_pressure_preserves_retry_hint() {
        let err = CreateError::Cell(Box::new(CellSchedulerError::PressureSaturated));
        let sandbox_err: crate::error::SandboxError = err.into();
        assert!(matches!(
            sandbox_err,
            crate::error::SandboxError::PlacementThrottled { .. }
        ));

        let err = CreateError::Cell(Box::new(CellSchedulerError::AllHostsDraining));
        let sandbox_err: crate::error::SandboxError = err.into();
        assert!(matches!(
            sandbox_err,
            crate::error::SandboxError::Unprocessable(_)
        ));
    }
}
